from playwright.sync_api._generated import Page
import pytest #for testing framework
import time     #to set dealy
from playwright.sync_api import sync_playwright     #for browser automation
def browser (page): #Setup browser
    with sync_playwright () as p:
        browser = p.chromium.launch(slow_mo=5000)
        context = browser.new_context()
        page = context.new_page()
        yield browser
        context.close()
        browser()
def test_new_user (page): 
    #enter vaild details and create new user
    page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    time.sleep(2)
    page.fill("input[name='username']","Admin") 
    time.sleep(2)
    page.fill("input[placeholder='Password']","admin123")
    time.sleep(2)
    page.click("button[type='submit']")
    time.sleep(2)
    page.click("//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a/span")
    time.sleep(2)
    page.click ("//*[@id='app']/div[1]/div[2]/div[2]/div/div[2]/div[1]/button")
    time.sleep(5)
    page.click("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[1]/div/div[2]/div/div")
    time.sleep(5)
    page.get_by_role("option[name='Admin']").click()
    time.sleep(2)
    page.fill("input[placeholder='Type for hints...']","orange")
    time.sleep(2)
    page.get_by_role("option[name='Orange Test']").click()
    time.sleep(2)
    page.click("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[3]/div/div[2]/div/div")
    time.sleep(2)
    page.get_by_role("option[name='Enabled']").dblclick()
    time.sleep(2)
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[4]/div/div[2]/input","87197Vishwanath2378667")
    time.sleep(2)
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[1]/div/div[2]/input","Admin@123")
    time.sleep(2)
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/div/div[2]/input","Admin@123")
    time.sleep(2)
    page.click("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[3]/button[2]")
    
    
def test_password_1(page):
    page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    time.sleep(2)
    page.fill("input[name='username']","Admin") 
    time.sleep(2)
    page.fill("input[placeholder='Password']","admin123")
    time.sleep(2)
    page.click("button[type='submit']")
    time.sleep(2)
    page.click("//*[@id='app']/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a/span")
    time.sleep(2)
    page.click ("//*[@id='app']/div[1]/div[2]/div[2]/div/div[2]/div[1]/button")
    time.sleep(5)
    page.click("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[1]/div/div[2]/div/div")
    time.sleep(5)
    page.get_by_role("option[name='Admin']").click()
    time.sleep(2)
    page.fill("input[placeholder='Type for hints...']","orange")
    time.sleep(2)
    page.get_by_role("option[name='Orange Test']").click()
    time.sleep(2)
    page.click("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[3]/div/div[2]/div/div")
    time.sleep(2)
    page.get_by_role("option[name='Enabled']").dblclick()
    time.sleep(2)
    ##Testing validation of password and chose password
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div[4]/div/div[2]/input","618771Vishwanath328989")
    time.sleep(2)
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[1]/div/div[2]/input","")
    time.sleep(2)
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/div/div[2]/input","")
    time.sleep(2)
    page.click("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[3]/button[2]")
    time.sleep(2)
    assert page.url == "https://opensource-demo.orangehrmlive.com/web/index.php/admin/saveSystemUser",f"Need to set password mandatory"   
    time.sleep(2)
    #Testing validation of password and chose password
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[1]/div/div[2]/input","Admin123")
    time.sleep(2)
    page.fill("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/div/div[2]/input","admin123")
    time.sleep(2)
    page.click("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[3]/button[2]")
    time.sleep(2)
    assert page.url == "https://opensource-demo.orangehrmlive.com/web/index.php/admin/saveSystemUser",f"password fiedl are not case sensitive"
    time.sleep(3)
    error_message =page.locator("//*[@id='app']/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/div/span").text_content()
    assert "Passwords do not match" in error_message,"Error message is not present or it is chnaged"
    time.sleep(3)